/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo.submodule.lib

class Library {
    fun hello(message: String): String {
        return "lib -> $message"
    }
}